@baseUrl = http://localhost:5165/api
@contentType = application/json


### Create Borrow
POST {{baseUrl}}/Borrows/borrow
Content-Type: {{contentType}}

{
    "clientId": 1,
    "copyId": 36
}

### Return Borrow
POST {{baseUrl}}/Borrows/return
Content-Type: {{contentType}}

{
    "borrowingId": 5,
    "copyId": 36
}

### Get Full Borrow Details
GET {{baseUrl}}/Borrows/client/1
Content-Type: {{contentType}}

{
    "pageNumber": 1,
    "pageSize": 10,
    "clientId": 1
}