### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=JetBrains Rider

###
@baseUrl = http://localhost:5165/api

POST {{baseUrl}}/Clients
Content-Type: application/json

{
  "email": "Mohammad@gmail.com",
  "password": "Mohammad1234#",
  "firstName": "Mohammad",
  "lastName": "Atieh",
  "phoneNumber": "0780830732",
  "address": "Al-Zarqa",
  "userName": "Mohammad",
  "countryId": 113,
  "birthDate": "1973-10-06",
  "imageUrl": "",
  "libraryCardNumber": "230221"
}

###
GET {{baseUrl}}/Clients?pageNumber=1&pageSize=10
Content-Type: application/json

###
Put {{baseUrl}}/Clients/update-client-info/1
Content-Type: application/json

{
  "userId" : 1,
  "firstName": "Mohammad",
  "lastName": "Atieh",
  "address": "Al-Zarqa",
  "libraryCardNumber": "230221",
  "phoneNumber": "0780830732",
  "email": "Mohammad@gmail.com",
  "userName": "Mohammad",
  "imageUrl": "",
  "dateOfBirth": "1973-10-06",
  "countryId": 113
}

###
DELETE {{baseUrl}}/Clients/delete-client/1
Content-Type: application/json


###
PUT {{baseUrl}}/Clients/resotre-client/1
Content-Type: application/json