### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=JetBrains Rider

###
@baseUrl = http://localhost:5165/api/

POST {{baseUrl}}/Clients
Content-Type: application/json

{
  "email": "Mohammad@gmail.com",
  "password": "Mohammad1234#",
  "firstName": "Mohammad",
  "lastName": "Atieh",
  "phoneNumber": "0780830732",
  "address": "Al-Zarqa",
  "userName": "Mohammad",
  "countryId": 113,
  "birthDate": "1973-10-06",
  "imageUrl": "",
  "libraryCardNumber": "230221"
}

###
GET {{baseUrl}}/Clients?PageNumber=1&PageSize=10
Content-Type: application/json
