@baseUrl = http://localhost:5165/api
@contentType = application/json


### Create Borrow
POST {{baseUrl}}/Borrows/borrow
Content-Type: {{contentType}}

{
    "clientId": 4,
    "copyId": 7
}

### Return Borrow
POST {{baseUrl}}/Borrows/return
Content-Type: {{contentType}}

{
    "borrowingId": 16,
    "copyId": 7 
}

### Get Full Borrow Details
GET {{baseUrl}}/Borrows/client/3
Content-Type: {{contentType}}

{
    "pageNumber": 1,
    "pageSize": 10,
    "clientId": 3
}