@baseUrl = http://localhost:5165/api
@contentType = application/json


### Get fines for client
GET {{baseUrl}}/Fines/client/4
Content-Type: {{contentType}}

{
    "pageNumber": 1,
    "pageSize": 10,
    "clientId": 4
}

### check Fines status for borrowing
GET {{baseUrl}}/Fines/16/check
Content-Type: {{contentType}}

### Pay Fine
PUT {{baseUrl}}/Fines/1/pay
Content-Type: {{contentType}}